version: '3.10'

services:
  db20:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web20:
    build: .
    command: >
      bash -c "python manage.py collectstatic --no-input &&
               python manage.py migrate &&
               python manage.py createsuperuser --no-input --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL || true &&
               gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8020"
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8020:8020"
    depends_on:
      - db
    env_file:
      - .env